project_id = "isgfgclplfovvtlmitia"

[functions.zoom-connect-start]
verify_jwt = false

[functions.zoom-oauth-callback]
verify_jwt = false

[functions.zoom-generate-signature]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.check-overdue-payments]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.s3-get-upload-url]
verify_jwt = false

[functions.s3-get-signed-url]
verify_jwt = false
